name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # Variables for environment
    env:
      NODE_ENV: ${GITHUB_REF_SLUG} # Environment set based on branch name

    # Install dependencies
    - name: Install dependencies
      run: |
        cd frontend # Change frontend to your repo directory
        npm install
        cd ../backend # or adjust for backend
        npm install

    # Build the Docker images
    - name: Build the Docker images
      run: |
        docker build ./frontend -t registry.github.com/<your-account>/<repo>/frontend:latest
        docker build ./backend -t registry.github.com/<your-account>/<repo>/backend:latest

    # Log into Docker registry
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        username: ${{ github.actor }} 
        password: ${{ secrets.GITHUB_TOKEN }}
        
    # Push Docker images (Ensure your repository is public or private and set secrets as needed)
    - name: Push Docker images
      run: |
        docker push registry.github.com/<your-account>/<repo>/frontend:latest
        docker push registry.github.com/<your-account>/<repo>/backend:latest

  # Add additional jobs for staging or production deployment if needed
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Deploy only from main branch
    needs: [build]

    steps:
    - uses: actions/checkout@v2
    - name: Deploy with kubectl
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG_PATH }} # Path/reference to your kubeconfig
      run: |
        kubectl apply -f k8s/deployment.yaml -n your-namespace # Adjust namespace
        kubectl set image deployment/your-deployment-name container-section=registry.github.com/<your-account>/<repo>/frontend:latest -n your-namespace # Update frontend
        kubectl set image deployment/your-deployment-name container-section=registry.github.com/<your-account>/<repo>/backend:latest -n your-namespace # Update 
        
